/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AAAdd extends PAdd
{
    private PMult _mult_;

    public AAAdd ()
    {
    }

    public AAAdd (
            PMult _mult_
    )
    {
        setMult (_mult_);
    }

    public Object clone()
    {
        return new AAAdd (
            (PMult)cloneNode (_mult_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAdd(this);
    }

    public PMult getMult ()
    {
        return _mult_;
    }

    public void setMult (PMult node)
    {
        if(_mult_ != null)
        {
            _mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mult_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_mult_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _mult_ == child )
        {
            _mult_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _mult_ == oldChild )
        {
            setMult ((PMult) newChild);
            return;
        }
    }

}
