/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AABooleanfunction extends PBooleanfunction
{
    private TKeywordAnd _keyword_and_;

    public AABooleanfunction ()
    {
    }

    public AABooleanfunction (
            TKeywordAnd _keyword_and_
    )
    {
        setKeywordAnd (_keyword_and_);
    }

    public Object clone()
    {
        return new AABooleanfunction (
            (TKeywordAnd)cloneNode (_keyword_and_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAABooleanfunction(this);
    }

    public TKeywordAnd getKeywordAnd ()
    {
        return _keyword_and_;
    }

    public void setKeywordAnd (TKeywordAnd node)
    {
        if(_keyword_and_ != null)
        {
            _keyword_and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_and_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_and_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_and_ == child )
        {
            _keyword_and_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_and_ == oldChild )
        {
            setKeywordAnd ((TKeywordAnd) newChild);
            return;
        }
    }

}
