/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AAComparisonfunction extends PComparisonfunction
{
    private TKeywordLt _keyword_lt_;

    public AAComparisonfunction ()
    {
    }

    public AAComparisonfunction (
            TKeywordLt _keyword_lt_
    )
    {
        setKeywordLt (_keyword_lt_);
    }

    public Object clone()
    {
        return new AAComparisonfunction (
            (TKeywordLt)cloneNode (_keyword_lt_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAComparisonfunction(this);
    }

    public TKeywordLt getKeywordLt ()
    {
        return _keyword_lt_;
    }

    public void setKeywordLt (TKeywordLt node)
    {
        if(_keyword_lt_ != null)
        {
            _keyword_lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_lt_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_lt_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_lt_ == child )
        {
            _keyword_lt_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_lt_ == oldChild )
        {
            setKeywordLt ((TKeywordLt) newChild);
            return;
        }
    }

}
