/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AADeclarefirst extends PDeclarefirst
{
    private PDeclarefirstnormal _declarefirstnormal_;

    public AADeclarefirst ()
    {
    }

    public AADeclarefirst (
            PDeclarefirstnormal _declarefirstnormal_
    )
    {
        setDeclarefirstnormal (_declarefirstnormal_);
    }

    public Object clone()
    {
        return new AADeclarefirst (
            (PDeclarefirstnormal)cloneNode (_declarefirstnormal_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAADeclarefirst(this);
    }

    public PDeclarefirstnormal getDeclarefirstnormal ()
    {
        return _declarefirstnormal_;
    }

    public void setDeclarefirstnormal (PDeclarefirstnormal node)
    {
        if(_declarefirstnormal_ != null)
        {
            _declarefirstnormal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _declarefirstnormal_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_declarefirstnormal_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _declarefirstnormal_ == child )
        {
            _declarefirstnormal_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _declarefirstnormal_ == oldChild )
        {
            setDeclarefirstnormal ((PDeclarefirstnormal) newChild);
            return;
        }
    }

}
