/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AADocumentinside extends PDocumentinside
{
    private PDeclarefirstlist _declarefirstlist_;

    public AADocumentinside ()
    {
    }

    public AADocumentinside (
            PDeclarefirstlist _declarefirstlist_
    )
    {
        setDeclarefirstlist (_declarefirstlist_);
    }

    public Object clone()
    {
        return new AADocumentinside (
            (PDeclarefirstlist)cloneNode (_declarefirstlist_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAADocumentinside(this);
    }

    public PDeclarefirstlist getDeclarefirstlist ()
    {
        return _declarefirstlist_;
    }

    public void setDeclarefirstlist (PDeclarefirstlist node)
    {
        if(_declarefirstlist_ != null)
        {
            _declarefirstlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _declarefirstlist_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_declarefirstlist_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _declarefirstlist_ == child )
        {
            _declarefirstlist_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _declarefirstlist_ == oldChild )
        {
            setDeclarefirstlist ((PDeclarefirstlist) newChild);
            return;
        }
    }

}
