/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AAIfexpr extends PIfexpr
{
    private PSimple _simple_;

    public AAIfexpr ()
    {
    }

    public AAIfexpr (
            PSimple _simple_
    )
    {
        setSimple (_simple_);
    }

    public Object clone()
    {
        return new AAIfexpr (
            (PSimple)cloneNode (_simple_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIfexpr(this);
    }

    public PSimple getSimple ()
    {
        return _simple_;
    }

    public void setSimple (PSimple node)
    {
        if(_simple_ != null)
        {
            _simple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _simple_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_simple_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _simple_ == child )
        {
            _simple_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _simple_ == oldChild )
        {
            setSimple ((PSimple) newChild);
            return;
        }
    }

}
