/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AAType extends PType
{
    private TKeywordDyn _keyword_dyn_;

    public AAType ()
    {
    }

    public AAType (
            TKeywordDyn _keyword_dyn_
    )
    {
        setKeywordDyn (_keyword_dyn_);
    }

    public Object clone()
    {
        return new AAType (
            (TKeywordDyn)cloneNode (_keyword_dyn_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAType(this);
    }

    public TKeywordDyn getKeywordDyn ()
    {
        return _keyword_dyn_;
    }

    public void setKeywordDyn (TKeywordDyn node)
    {
        if(_keyword_dyn_ != null)
        {
            _keyword_dyn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_dyn_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_dyn_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_dyn_ == child )
        {
            _keyword_dyn_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_dyn_ == oldChild )
        {
            setKeywordDyn ((TKeywordDyn) newChild);
            return;
        }
    }

}
