/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABBlock extends PBlock
{
    private PTabblock _tabblock_;

    public ABBlock ()
    {
    }

    public ABBlock (
            PTabblock _tabblock_
    )
    {
        setTabblock (_tabblock_);
    }

    public Object clone()
    {
        return new ABBlock (
            (PTabblock)cloneNode (_tabblock_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABBlock(this);
    }

    public PTabblock getTabblock ()
    {
        return _tabblock_;
    }

    public void setTabblock (PTabblock node)
    {
        if(_tabblock_ != null)
        {
            _tabblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tabblock_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_tabblock_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _tabblock_ == child )
        {
            _tabblock_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _tabblock_ == oldChild )
        {
            setTabblock ((PTabblock) newChild);
            return;
        }
    }

}
