/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABBooleanfunction extends PBooleanfunction
{
    private TKeywordNand _keyword_nand_;

    public ABBooleanfunction ()
    {
    }

    public ABBooleanfunction (
            TKeywordNand _keyword_nand_
    )
    {
        setKeywordNand (_keyword_nand_);
    }

    public Object clone()
    {
        return new ABBooleanfunction (
            (TKeywordNand)cloneNode (_keyword_nand_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABBooleanfunction(this);
    }

    public TKeywordNand getKeywordNand ()
    {
        return _keyword_nand_;
    }

    public void setKeywordNand (TKeywordNand node)
    {
        if(_keyword_nand_ != null)
        {
            _keyword_nand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_nand_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_nand_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_nand_ == child )
        {
            _keyword_nand_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_nand_ == oldChild )
        {
            setKeywordNand ((TKeywordNand) newChild);
            return;
        }
    }

}
