/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABExpression extends PExpression
{
    private PBooleanlogic _booleanlogic_;

    public ABExpression ()
    {
    }

    public ABExpression (
            PBooleanlogic _booleanlogic_
    )
    {
        setBooleanlogic (_booleanlogic_);
    }

    public Object clone()
    {
        return new ABExpression (
            (PBooleanlogic)cloneNode (_booleanlogic_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABExpression(this);
    }

    public PBooleanlogic getBooleanlogic ()
    {
        return _booleanlogic_;
    }

    public void setBooleanlogic (PBooleanlogic node)
    {
        if(_booleanlogic_ != null)
        {
            _booleanlogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _booleanlogic_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_booleanlogic_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _booleanlogic_ == child )
        {
            _booleanlogic_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _booleanlogic_ == oldChild )
        {
            setBooleanlogic ((PBooleanlogic) newChild);
            return;
        }
    }

}
