/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABIfexpr extends PIfexpr
{
    private PTest _test_;

    public ABIfexpr ()
    {
    }

    public ABIfexpr (
            PTest _test_
    )
    {
        setTest (_test_);
    }

    public Object clone()
    {
        return new ABIfexpr (
            (PTest)cloneNode (_test_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABIfexpr(this);
    }

    public PTest getTest ()
    {
        return _test_;
    }

    public void setTest (PTest node)
    {
        if(_test_ != null)
        {
            _test_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _test_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_test_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _test_ == child )
        {
            _test_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _test_ == oldChild )
        {
            setTest ((PTest) newChild);
            return;
        }
    }

}
