/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABParameterlist extends PParameterlist
{
    private PParameterlist _parameterlist_;
    private TOperatorComma _operator_comma_;
    private PParameter _parameter_;

    public ABParameterlist ()
    {
    }

    public ABParameterlist (
            PParameterlist _parameterlist_,
            TOperatorComma _operator_comma_,
            PParameter _parameter_
    )
    {
        setParameterlist (_parameterlist_);
        setOperatorComma (_operator_comma_);
        setParameter (_parameter_);
    }

    public Object clone()
    {
        return new ABParameterlist (
            (PParameterlist)cloneNode (_parameterlist_),
            (TOperatorComma)cloneNode (_operator_comma_),
            (PParameter)cloneNode (_parameter_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABParameterlist(this);
    }

    public PParameterlist getParameterlist ()
    {
        return _parameterlist_;
    }

    public void setParameterlist (PParameterlist node)
    {
        if(_parameterlist_ != null)
        {
            _parameterlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parameterlist_ = node;
    }
    public TOperatorComma getOperatorComma ()
    {
        return _operator_comma_;
    }

    public void setOperatorComma (TOperatorComma node)
    {
        if(_operator_comma_ != null)
        {
            _operator_comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operator_comma_ = node;
    }
    public PParameter getParameter ()
    {
        return _parameter_;
    }

    public void setParameter (PParameter node)
    {
        if(_parameter_ != null)
        {
            _parameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parameter_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_parameterlist_)
            + toString (_operator_comma_)
            + toString (_parameter_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _parameterlist_ == child )
        {
            _parameterlist_ = null;
            return;
        }
        if ( _operator_comma_ == child )
        {
            _operator_comma_ = null;
            return;
        }
        if ( _parameter_ == child )
        {
            _parameter_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _parameterlist_ == oldChild )
        {
            setParameterlist ((PParameterlist) newChild);
            return;
        }
        if ( _operator_comma_ == oldChild )
        {
            setOperatorComma ((TOperatorComma) newChild);
            return;
        }
        if ( _parameter_ == oldChild )
        {
            setParameter ((PParameter) newChild);
            return;
        }
    }

}
