/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABraceblock extends PBraceblock
{
    private TOperatorOpeningBrace _operator_opening_brace_;
    private PBraceblockinside _braceblockinside_;
    private TOperatorClosingBrace _operator_closing_brace_;

    public ABraceblock ()
    {
    }

    public ABraceblock (
            TOperatorOpeningBrace _operator_opening_brace_,
            PBraceblockinside _braceblockinside_,
            TOperatorClosingBrace _operator_closing_brace_
    )
    {
        setOperatorOpeningBrace (_operator_opening_brace_);
        setBraceblockinside (_braceblockinside_);
        setOperatorClosingBrace (_operator_closing_brace_);
    }

    public Object clone()
    {
        return new ABraceblock (
            (TOperatorOpeningBrace)cloneNode (_operator_opening_brace_),
            (PBraceblockinside)cloneNode (_braceblockinside_),
            (TOperatorClosingBrace)cloneNode (_operator_closing_brace_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABraceblock(this);
    }

    public TOperatorOpeningBrace getOperatorOpeningBrace ()
    {
        return _operator_opening_brace_;
    }

    public void setOperatorOpeningBrace (TOperatorOpeningBrace node)
    {
        if(_operator_opening_brace_ != null)
        {
            _operator_opening_brace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operator_opening_brace_ = node;
    }
    public PBraceblockinside getBraceblockinside ()
    {
        return _braceblockinside_;
    }

    public void setBraceblockinside (PBraceblockinside node)
    {
        if(_braceblockinside_ != null)
        {
            _braceblockinside_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _braceblockinside_ = node;
    }
    public TOperatorClosingBrace getOperatorClosingBrace ()
    {
        return _operator_closing_brace_;
    }

    public void setOperatorClosingBrace (TOperatorClosingBrace node)
    {
        if(_operator_closing_brace_ != null)
        {
            _operator_closing_brace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operator_closing_brace_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_operator_opening_brace_)
            + toString (_braceblockinside_)
            + toString (_operator_closing_brace_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _operator_opening_brace_ == child )
        {
            _operator_opening_brace_ = null;
            return;
        }
        if ( _braceblockinside_ == child )
        {
            _braceblockinside_ = null;
            return;
        }
        if ( _operator_closing_brace_ == child )
        {
            _operator_closing_brace_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _operator_opening_brace_ == oldChild )
        {
            setOperatorOpeningBrace ((TOperatorOpeningBrace) newChild);
            return;
        }
        if ( _braceblockinside_ == oldChild )
        {
            setBraceblockinside ((PBraceblockinside) newChild);
            return;
        }
        if ( _operator_closing_brace_ == oldChild )
        {
            setOperatorClosingBrace ((TOperatorClosingBrace) newChild);
            return;
        }
    }

}
