/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ABScopealteration extends PScopealteration
{
    private PUsing _using_;

    public ABScopealteration ()
    {
    }

    public ABScopealteration (
            PUsing _using_
    )
    {
        setUsing (_using_);
    }

    public Object clone()
    {
        return new ABScopealteration (
            (PUsing)cloneNode (_using_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABScopealteration(this);
    }

    public PUsing getUsing ()
    {
        return _using_;
    }

    public void setUsing (PUsing node)
    {
        if(_using_ != null)
        {
            _using_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _using_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_using_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _using_ == child )
        {
            _using_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _using_ == oldChild )
        {
            setUsing ((PUsing) newChild);
            return;
        }
    }

}
