/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ACBlock extends PBlock
{
    private PBracetabblock _bracetabblock_;

    public ACBlock ()
    {
    }

    public ACBlock (
            PBracetabblock _bracetabblock_
    )
    {
        setBracetabblock (_bracetabblock_);
    }

    public Object clone()
    {
        return new ACBlock (
            (PBracetabblock)cloneNode (_bracetabblock_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACBlock(this);
    }

    public PBracetabblock getBracetabblock ()
    {
        return _bracetabblock_;
    }

    public void setBracetabblock (PBracetabblock node)
    {
        if(_bracetabblock_ != null)
        {
            _bracetabblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bracetabblock_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_bracetabblock_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _bracetabblock_ == child )
        {
            _bracetabblock_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _bracetabblock_ == oldChild )
        {
            setBracetabblock ((PBracetabblock) newChild);
            return;
        }
    }

}
