/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ACComparisonfunction extends PComparisonfunction
{
    private TKeywordEql _keyword_eql_;

    public ACComparisonfunction ()
    {
    }

    public ACComparisonfunction (
            TKeywordEql _keyword_eql_
    )
    {
        setKeywordEql (_keyword_eql_);
    }

    public Object clone()
    {
        return new ACComparisonfunction (
            (TKeywordEql)cloneNode (_keyword_eql_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACComparisonfunction(this);
    }

    public TKeywordEql getKeywordEql ()
    {
        return _keyword_eql_;
    }

    public void setKeywordEql (TKeywordEql node)
    {
        if(_keyword_eql_ != null)
        {
            _keyword_eql_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_eql_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_eql_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_eql_ == child )
        {
            _keyword_eql_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_eql_ == oldChild )
        {
            setKeywordEql ((TKeywordEql) newChild);
            return;
        }
    }

}
