/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ACPrimary extends PPrimary
{
    private TRational _rational_;

    public ACPrimary ()
    {
    }

    public ACPrimary (
            TRational _rational_
    )
    {
        setRational (_rational_);
    }

    public Object clone()
    {
        return new ACPrimary (
            (TRational)cloneNode (_rational_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACPrimary(this);
    }

    public TRational getRational ()
    {
        return _rational_;
    }

    public void setRational (TRational node)
    {
        if(_rational_ != null)
        {
            _rational_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rational_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_rational_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _rational_ == child )
        {
            _rational_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _rational_ == oldChild )
        {
            setRational ((TRational) newChild);
            return;
        }
    }

}
