/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ACSimple extends PSimple
{
    private PExtractmember _extractmember_;

    public ACSimple ()
    {
    }

    public ACSimple (
            PExtractmember _extractmember_
    )
    {
        setExtractmember (_extractmember_);
    }

    public Object clone()
    {
        return new ACSimple (
            (PExtractmember)cloneNode (_extractmember_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACSimple(this);
    }

    public PExtractmember getExtractmember ()
    {
        return _extractmember_;
    }

    public void setExtractmember (PExtractmember node)
    {
        if(_extractmember_ != null)
        {
            _extractmember_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _extractmember_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_extractmember_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _extractmember_ == child )
        {
            _extractmember_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _extractmember_ == oldChild )
        {
            setExtractmember ((PExtractmember) newChild);
            return;
        }
    }

}
