/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ADeclarefirstnormal extends PDeclarefirstnormal
{
    private TKeywordDeclfirst _keyword_declfirst_;
    private TIdentifier _identifier_;
    private TOperatorAssign _operator_assign_;
    private PExpression _expression_;

    public ADeclarefirstnormal ()
    {
    }

    public ADeclarefirstnormal (
            TKeywordDeclfirst _keyword_declfirst_,
            TIdentifier _identifier_,
            TOperatorAssign _operator_assign_,
            PExpression _expression_
    )
    {
        setKeywordDeclfirst (_keyword_declfirst_);
        setIdentifier (_identifier_);
        setOperatorAssign (_operator_assign_);
        setExpression (_expression_);
    }

    public Object clone()
    {
        return new ADeclarefirstnormal (
            (TKeywordDeclfirst)cloneNode (_keyword_declfirst_),
            (TIdentifier)cloneNode (_identifier_),
            (TOperatorAssign)cloneNode (_operator_assign_),
            (PExpression)cloneNode (_expression_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarefirstnormal(this);
    }

    public TKeywordDeclfirst getKeywordDeclfirst ()
    {
        return _keyword_declfirst_;
    }

    public void setKeywordDeclfirst (TKeywordDeclfirst node)
    {
        if(_keyword_declfirst_ != null)
        {
            _keyword_declfirst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_declfirst_ = node;
    }
    public TIdentifier getIdentifier ()
    {
        return _identifier_;
    }

    public void setIdentifier (TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }
    public TOperatorAssign getOperatorAssign ()
    {
        return _operator_assign_;
    }

    public void setOperatorAssign (TOperatorAssign node)
    {
        if(_operator_assign_ != null)
        {
            _operator_assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operator_assign_ = node;
    }
    public PExpression getExpression ()
    {
        return _expression_;
    }

    public void setExpression (PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_declfirst_)
            + toString (_identifier_)
            + toString (_operator_assign_)
            + toString (_expression_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_declfirst_ == child )
        {
            _keyword_declfirst_ = null;
            return;
        }
        if ( _identifier_ == child )
        {
            _identifier_ = null;
            return;
        }
        if ( _operator_assign_ == child )
        {
            _operator_assign_ = null;
            return;
        }
        if ( _expression_ == child )
        {
            _expression_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_declfirst_ == oldChild )
        {
            setKeywordDeclfirst ((TKeywordDeclfirst) newChild);
            return;
        }
        if ( _identifier_ == oldChild )
        {
            setIdentifier ((TIdentifier) newChild);
            return;
        }
        if ( _operator_assign_ == oldChild )
        {
            setOperatorAssign ((TOperatorAssign) newChild);
            return;
        }
        if ( _expression_ == oldChild )
        {
            setExpression ((PExpression) newChild);
            return;
        }
    }

}
