/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ADSimple extends PSimple
{
    private PPrimary _primary_;

    public ADSimple ()
    {
    }

    public ADSimple (
            PPrimary _primary_
    )
    {
        setPrimary (_primary_);
    }

    public Object clone()
    {
        return new ADSimple (
            (PPrimary)cloneNode (_primary_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADSimple(this);
    }

    public PPrimary getPrimary ()
    {
        return _primary_;
    }

    public void setPrimary (PPrimary node)
    {
        if(_primary_ != null)
        {
            _primary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _primary_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_primary_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _primary_ == child )
        {
            _primary_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _primary_ == oldChild )
        {
            setPrimary ((PPrimary) newChild);
            return;
        }
    }

}
