/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AEComparisonfunction extends PComparisonfunction
{
    private TKeywordGt _keyword_gt_;

    public AEComparisonfunction ()
    {
    }

    public AEComparisonfunction (
            TKeywordGt _keyword_gt_
    )
    {
        setKeywordGt (_keyword_gt_);
    }

    public Object clone()
    {
        return new AEComparisonfunction (
            (TKeywordGt)cloneNode (_keyword_gt_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEComparisonfunction(this);
    }

    public TKeywordGt getKeywordGt ()
    {
        return _keyword_gt_;
    }

    public void setKeywordGt (TKeywordGt node)
    {
        if(_keyword_gt_ != null)
        {
            _keyword_gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_gt_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_gt_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_gt_ == child )
        {
            _keyword_gt_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_gt_ == oldChild )
        {
            setKeywordGt ((TKeywordGt) newChild);
            return;
        }
    }

}
