/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AElse extends PElse
{
    private TKeywordElse _keyword_else_;
    private PBlock _block_;

    public AElse ()
    {
    }

    public AElse (
            TKeywordElse _keyword_else_,
            PBlock _block_
    )
    {
        setKeywordElse (_keyword_else_);
        setBlock (_block_);
    }

    public Object clone()
    {
        return new AElse (
            (TKeywordElse)cloneNode (_keyword_else_),
            (PBlock)cloneNode (_block_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElse(this);
    }

    public TKeywordElse getKeywordElse ()
    {
        return _keyword_else_;
    }

    public void setKeywordElse (TKeywordElse node)
    {
        if(_keyword_else_ != null)
        {
            _keyword_else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_else_ = node;
    }
    public PBlock getBlock ()
    {
        return _block_;
    }

    public void setBlock (PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_else_)
            + toString (_block_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_else_ == child )
        {
            _keyword_else_ = null;
            return;
        }
        if ( _block_ == child )
        {
            _block_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_else_ == oldChild )
        {
            setKeywordElse ((TKeywordElse) newChild);
            return;
        }
        if ( _block_ == oldChild )
        {
            setBlock ((PBlock) newChild);
            return;
        }
    }

}
