/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AExpose extends PExpose
{
    private TKeywordExpose _keyword_expose_;
    private TIdentifier _identifier_;
    private TNewline _newline_;

    public AExpose ()
    {
    }

    public AExpose (
            TKeywordExpose _keyword_expose_,
            TIdentifier _identifier_,
            TNewline _newline_
    )
    {
        setKeywordExpose (_keyword_expose_);
        setIdentifier (_identifier_);
        setNewline (_newline_);
    }

    public Object clone()
    {
        return new AExpose (
            (TKeywordExpose)cloneNode (_keyword_expose_),
            (TIdentifier)cloneNode (_identifier_),
            (TNewline)cloneNode (_newline_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpose(this);
    }

    public TKeywordExpose getKeywordExpose ()
    {
        return _keyword_expose_;
    }

    public void setKeywordExpose (TKeywordExpose node)
    {
        if(_keyword_expose_ != null)
        {
            _keyword_expose_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_expose_ = node;
    }
    public TIdentifier getIdentifier ()
    {
        return _identifier_;
    }

    public void setIdentifier (TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }
    public TNewline getNewline ()
    {
        return _newline_;
    }

    public void setNewline (TNewline node)
    {
        if(_newline_ != null)
        {
            _newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _newline_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_expose_)
            + toString (_identifier_)
            + toString (_newline_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_expose_ == child )
        {
            _keyword_expose_ = null;
            return;
        }
        if ( _identifier_ == child )
        {
            _identifier_ = null;
            return;
        }
        if ( _newline_ == child )
        {
            _newline_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_expose_ == oldChild )
        {
            setKeywordExpose ((TKeywordExpose) newChild);
            return;
        }
        if ( _identifier_ == oldChild )
        {
            setIdentifier ((TIdentifier) newChild);
            return;
        }
        if ( _newline_ == oldChild )
        {
            setNewline ((TNewline) newChild);
            return;
        }
    }

}
