/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AFBooleanfunction extends PBooleanfunction
{
    private TKeywordXnor _keyword_xnor_;

    public AFBooleanfunction ()
    {
    }

    public AFBooleanfunction (
            TKeywordXnor _keyword_xnor_
    )
    {
        setKeywordXnor (_keyword_xnor_);
    }

    public Object clone()
    {
        return new AFBooleanfunction (
            (TKeywordXnor)cloneNode (_keyword_xnor_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFBooleanfunction(this);
    }

    public TKeywordXnor getKeywordXnor ()
    {
        return _keyword_xnor_;
    }

    public void setKeywordXnor (TKeywordXnor node)
    {
        if(_keyword_xnor_ != null)
        {
            _keyword_xnor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_xnor_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_xnor_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_xnor_ == child )
        {
            _keyword_xnor_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_xnor_ == oldChild )
        {
            setKeywordXnor ((TKeywordXnor) newChild);
            return;
        }
    }

}
