/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class ATest extends PTest
{
    private PSimple _a_;
    private PComparisonfunction _comparisonfunction_;
    private PSimple _b_;

    public ATest ()
    {
    }

    public ATest (
            PSimple _a_,
            PComparisonfunction _comparisonfunction_,
            PSimple _b_
    )
    {
        setA (_a_);
        setComparisonfunction (_comparisonfunction_);
        setB (_b_);
    }

    public Object clone()
    {
        return new ATest (
            (PSimple)cloneNode (_a_),
            (PComparisonfunction)cloneNode (_comparisonfunction_),
            (PSimple)cloneNode (_b_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATest(this);
    }

    public PSimple getA ()
    {
        return _a_;
    }

    public void setA (PSimple node)
    {
        if(_a_ != null)
        {
            _a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _a_ = node;
    }
    public PComparisonfunction getComparisonfunction ()
    {
        return _comparisonfunction_;
    }

    public void setComparisonfunction (PComparisonfunction node)
    {
        if(_comparisonfunction_ != null)
        {
            _comparisonfunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonfunction_ = node;
    }
    public PSimple getB ()
    {
        return _b_;
    }

    public void setB (PSimple node)
    {
        if(_b_ != null)
        {
            _b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _b_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_a_)
            + toString (_comparisonfunction_)
            + toString (_b_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _a_ == child )
        {
            _a_ = null;
            return;
        }
        if ( _comparisonfunction_ == child )
        {
            _comparisonfunction_ = null;
            return;
        }
        if ( _b_ == child )
        {
            _b_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _a_ == oldChild )
        {
            setA ((PSimple) newChild);
            return;
        }
        if ( _comparisonfunction_ == oldChild )
        {
            setComparisonfunction ((PComparisonfunction) newChild);
            return;
        }
        if ( _b_ == oldChild )
        {
            setB ((PSimple) newChild);
            return;
        }
    }

}
