/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import java.util.*;
import Dextr.Sablecc.analysis.*;

public final class AUsing extends PUsing
{
    private TKeywordUsing _keyword_using_;
    private TIdentifier _identifier_;
    private TNewline _newline_;

    public AUsing ()
    {
    }

    public AUsing (
            TKeywordUsing _keyword_using_,
            TIdentifier _identifier_,
            TNewline _newline_
    )
    {
        setKeywordUsing (_keyword_using_);
        setIdentifier (_identifier_);
        setNewline (_newline_);
    }

    public Object clone()
    {
        return new AUsing (
            (TKeywordUsing)cloneNode (_keyword_using_),
            (TIdentifier)cloneNode (_identifier_),
            (TNewline)cloneNode (_newline_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUsing(this);
    }

    public TKeywordUsing getKeywordUsing ()
    {
        return _keyword_using_;
    }

    public void setKeywordUsing (TKeywordUsing node)
    {
        if(_keyword_using_ != null)
        {
            _keyword_using_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _keyword_using_ = node;
    }
    public TIdentifier getIdentifier ()
    {
        return _identifier_;
    }

    public void setIdentifier (TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }
    public TNewline getNewline ()
    {
        return _newline_;
    }

    public void setNewline (TNewline node)
    {
        if(_newline_ != null)
        {
            _newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _newline_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_keyword_using_)
            + toString (_identifier_)
            + toString (_newline_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _keyword_using_ == child )
        {
            _keyword_using_ = null;
            return;
        }
        if ( _identifier_ == child )
        {
            _identifier_ = null;
            return;
        }
        if ( _newline_ == child )
        {
            _newline_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _keyword_using_ == oldChild )
        {
            setKeywordUsing ((TKeywordUsing) newChild);
            return;
        }
        if ( _identifier_ == oldChild )
        {
            setIdentifier ((TIdentifier) newChild);
            return;
        }
        if ( _newline_ == oldChild )
        {
            setNewline ((TNewline) newChild);
            return;
        }
    }

}
