/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TIndentOpen extends Token
{
    public TIndentOpen()
    {
        super.setText("xxxIndentOpen");
    }

    public TIndentOpen(int line, int pos)
    {
        super.setText("xxxIndentOpen");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIndentOpen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIndentOpen(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TIndentOpen text.");
    }
}
