/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordDeclfirst extends Token
{
    public TKeywordDeclfirst()
    {
        super.setText("declfirst");
    }

    public TKeywordDeclfirst(int line, int pos)
    {
        super.setText("declfirst");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordDeclfirst(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordDeclfirst(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordDeclfirst text.");
    }
}
