/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordDyn extends Token
{
    public TKeywordDyn()
    {
        super.setText("dyn");
    }

    public TKeywordDyn(int line, int pos)
    {
        super.setText("dyn");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordDyn(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordDyn(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordDyn text.");
    }
}
