/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordXor extends Token
{
    public TKeywordXor()
    {
        super.setText("xor");
    }

    public TKeywordXor(int line, int pos)
    {
        super.setText("xor");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordXor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordXor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordXor text.");
    }
}
