/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordNor extends Token
{
    public TKeywordNor()
    {
        super.setText("nor");
    }

    public TKeywordNor(int line, int pos)
    {
        super.setText("nor");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordNor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordNor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordNor text.");
    }
}
