/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordNand extends Token
{
    public TKeywordNand()
    {
        super.setText("nand");
    }

    public TKeywordNand(int line, int pos)
    {
        super.setText("nand");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordNand(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordNand(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordNand text.");
    }
}
