/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordIf extends Token
{
    public TKeywordIf()
    {
        super.setText("if");
    }

    public TKeywordIf(int line, int pos)
    {
        super.setText("if");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordIf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordIf(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordIf text.");
    }
}
