/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordDecl extends Token
{
    public TKeywordDecl()
    {
        super.setText("decl");
    }

    public TKeywordDecl(int line, int pos)
    {
        super.setText("decl");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordDecl(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordDecl(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordDecl text.");
    }
}
