/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordFunc extends Token
{
    public TKeywordFunc()
    {
        super.setText("func");
    }

    public TKeywordFunc(int line, int pos)
    {
        super.setText("func");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordFunc(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordFunc(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordFunc text.");
    }
}
