/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordLte extends Token
{
    public TKeywordLte()
    {
        super.setText("lte");
    }

    public TKeywordLte(int line, int pos)
    {
        super.setText("lte");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordLte(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordLte(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordLte text.");
    }
}
