/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordGte extends Token
{
    public TKeywordGte()
    {
        super.setText("gte");
    }

    public TKeywordGte(int line, int pos)
    {
        super.setText("gte");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordGte(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordGte(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordGte text.");
    }
}
