/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordFrom extends Token
{
    public TKeywordFrom()
    {
        super.setText("from");
    }

    public TKeywordFrom(int line, int pos)
    {
        super.setText("from");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordFrom(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordFrom(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordFrom text.");
    }
}
