/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TKeywordVoid extends Token
{
    public TKeywordVoid()
    {
        super.setText("void");
    }

    public TKeywordVoid(int line, int pos)
    {
        super.setText("void");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKeywordVoid(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordVoid(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKeywordVoid text.");
    }
}
