/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TOperatorAssign extends Token
{
    public TOperatorAssign()
    {
        super.setText("=");
    }

    public TOperatorAssign(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOperatorAssign(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperatorAssign(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOperatorAssign text.");
    }
}
