/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TOperatorMinus extends Token
{
    public TOperatorMinus()
    {
        super.setText("-");
    }

    public TOperatorMinus(int line, int pos)
    {
        super.setText("-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOperatorMinus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperatorMinus(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOperatorMinus text.");
    }
}
