/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TOperatorComma extends Token
{
    public TOperatorComma()
    {
        super.setText(",");
    }

    public TOperatorComma(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOperatorComma(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperatorComma(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOperatorComma text.");
    }
}
