/* This file was generated by SableCC (http://www.sablecc.org/). */

package Dextr.Sablecc.node;

import Dextr.Sablecc.analysis.*;

public final class TOperatorClosingBrace extends Token
{
    public TOperatorClosingBrace()
    {
        super.setText("}");
    }

    public TOperatorClosingBrace(int line, int pos)
    {
        super.setText("}");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOperatorClosingBrace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperatorClosingBrace(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOperatorClosingBrace text.");
    }
}
