/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using Fujin.Sablecc.node;

namespace Fujin.Sablecc.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = New25(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = New26(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = New27(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = New28(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = New29(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = New30(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = New31(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = New32(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = New33(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = New34(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = New35(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = New36(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = New37(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = New38(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = New39(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = New40(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            Token token = New41(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            Token token = New42(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            Token token = New43(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            Token token = New44(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            Token token = New45(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            Token token = New46(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            Token token = New47(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            Token token = New48(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TOperatorMinus(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TOperatorPlus(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TOperatorClosingParenthesis(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TKeywordLt(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TKeywordFor(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TKeywordOr(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TKeywordDyn(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TOperatorTimes(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TKeywordImport(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new TKeywordNand(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TKeywordGte(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TKeywordDne(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TKeywordPlane(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TOperatorClosingBrace(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TKeywordFrom(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TKeywordElse(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TKeywordElif(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TOperatorDivide(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TKeywordDeclfirst(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TKeywordGt(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TOperatorOpeningBrace(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new TKeywordIf(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TOperatorOpeningParenthesis(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TKeywordVoid(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TKeywordAnd(text, line, pos); }
    private Token New25(String text, int line, int pos) { return new TKeywordXnor(text, line, pos); }
    private Token New26(String text, int line, int pos) { return new TKeywordXor(text, line, pos); }
    private Token New27(String text, int line, int pos) { return new TKeywordNor(text, line, pos); }
    private Token New28(String text, int line, int pos) { return new TKeywordEql(text, line, pos); }
    private Token New29(String text, int line, int pos) { return new TKeywordTo(text, line, pos); }
    private Token New30(String text, int line, int pos) { return new TOperatorAssign(text, line, pos); }
    private Token New31(String text, int line, int pos) { return new TKeywordDecl(text, line, pos); }
    private Token New32(String text, int line, int pos) { return new TKeywordFunc(text, line, pos); }
    private Token New33(String text, int line, int pos) { return new TKeywordLte(text, line, pos); }
    private Token New34(String text, int line, int pos) { return new TKeywordUsing(text, line, pos); }
    private Token New35(String text, int line, int pos) { return new TKeywordExpose(text, line, pos); }
    private Token New36(String text, int line, int pos) { return new TOperatorExtractMember(text, line, pos); }
    private Token New37(String text, int line, int pos) { return new TOperatorComma(text, line, pos); }
    private Token New38(String text, int line, int pos) { return new TNewline(text, line, pos); }
    private Token New39(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    private Token New40(String text, int line, int pos) { return new TInteger(text, line, pos); }
    private Token New41(String text, int line, int pos) { return new TRational(text, line, pos); }
    private Token New42(String text, int line, int pos) { return new TString(text, line, pos); }
    private Token New43(String text, int line, int pos) { return new TTab(text, line, pos); }
    private Token New44(String text, int line, int pos) { return new TSpace(text, line, pos); }
    private Token New45(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    private Token New46(String text, int line, int pos) { return new TMultilineComment(text, line, pos); }
    private Token New47(String text, int line, int pos) { return new TIndentOpen(text, line, pos); }
    private Token New48(String text, int line, int pos) { return new TIndentClose(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {11, 12, 3},
          new int[] {13, 13, 2},
          new int[] {14, 31, 3},
          new int[] {32, 32, 4},
          new int[] {33, 33, 3},
          new int[] {34, 34, 5},
          new int[] {35, 35, 6},
          new int[] {36, 38, 3},
          new int[] {40, 40, 7},
          new int[] {41, 41, 8},
          new int[] {42, 42, 9},
          new int[] {43, 43, 10},
          new int[] {44, 44, 11},
          new int[] {45, 45, 12},
          new int[] {46, 46, 13},
          new int[] {47, 47, 14},
          new int[] {48, 57, 15},
          new int[] {58, 59, 3},
          new int[] {61, 61, 16},
          new int[] {63, 90, 3},
          new int[] {92, 92, 3},
          new int[] {94, 96, 3},
          new int[] {97, 97, 17},
          new int[] {98, 99, 3},
          new int[] {100, 100, 18},
          new int[] {101, 101, 19},
          new int[] {102, 102, 20},
          new int[] {103, 103, 21},
          new int[] {104, 104, 3},
          new int[] {105, 105, 22},
          new int[] {106, 107, 3},
          new int[] {108, 108, 23},
          new int[] {109, 109, 3},
          new int[] {110, 110, 24},
          new int[] {111, 111, 25},
          new int[] {112, 112, 26},
          new int[] {113, 115, 3},
          new int[] {116, 116, 27},
          new int[] {117, 117, 28},
          new int[] {118, 118, 29},
          new int[] {119, 119, 3},
          new int[] {120, 120, 30},
          new int[] {121, 122, 3},
          new int[] {123, 123, 31},
          new int[] {124, 124, 3},
          new int[] {125, 125, 32},
          new int[] {126, 65535, 3},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {11, 12, 33},
          new int[] {14, 31, 33},
          new int[] {33, 33, 33},
          new int[] {36, 38, 33},
          new int[] {48, 57, 34},
          new int[] {58, 59, 33},
          new int[] {63, 90, 33},
          new int[] {92, 92, 33},
          new int[] {94, 122, 33},
          new int[] {124, 124, 33},
          new int[] {126, 65535, 33},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {9, 33, 35},
          new int[] {34, 34, 36},
          new int[] {35, 47, 35},
          new int[] {58, 65535, 35},
        },
        new int[][] {
          new int[] {9, 9, 37},
          new int[] {11, 12, 37},
          new int[] {14, 65535, 37},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {42, 42, 38},
        },
        new int[][] {
          new int[] {46, 46, 39},
          new int[] {48, 57, 15},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 109, 33},
          new int[] {110, 110, 40},
          new int[] {111, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 100, 33},
          new int[] {101, 101, 41},
          new int[] {102, 109, 33},
          new int[] {110, 110, 42},
          new int[] {111, 120, 33},
          new int[] {121, 121, 43},
          new int[] {122, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 107, 33},
          new int[] {108, 108, 44},
          new int[] {109, 112, 33},
          new int[] {113, 113, 45},
          new int[] {114, 119, 33},
          new int[] {120, 120, 46},
          new int[] {121, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 110, 33},
          new int[] {111, 111, 47},
          new int[] {112, 113, 33},
          new int[] {114, 114, 48},
          new int[] {115, 116, 33},
          new int[] {117, 117, 49},
          new int[] {118, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 115, 33},
          new int[] {116, 116, 50},
          new int[] {117, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 101, 33},
          new int[] {102, 102, 51},
          new int[] {103, 108, 33},
          new int[] {109, 109, 52},
          new int[] {110, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 115, -23},
          new int[] {116, 116, 53},
          new int[] {117, 65535, -23},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 96, 33},
          new int[] {97, 97, 54},
          new int[] {98, 110, 33},
          new int[] {111, 111, 55},
          new int[] {112, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 113, 33},
          new int[] {114, 114, 56},
          new int[] {115, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 107, -21},
          new int[] {108, 108, 57},
          new int[] {109, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 58},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 114, 33},
          new int[] {115, 115, 59},
          new int[] {116, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 60},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 61},
          new int[] {111, 111, 62},
          new int[] {112, 119, 33},
          new int[] {120, 120, 63},
          new int[] {121, 65535, -21},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {9, 65535, -7},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {9, 65535, -8},
        },
        new int[][] {
          new int[] {9, 9, 64},
          new int[] {10, 10, 65},
          new int[] {11, 12, 64},
          new int[] {13, 13, 65},
          new int[] {14, 41, 64},
          new int[] {43, 65535, 64},
        },
        new int[][] {
          new int[] {48, 57, 66},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 99, 33},
          new int[] {100, 100, 67},
          new int[] {101, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 98, 33},
          new int[] {99, 99, 68},
          new int[] {100, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 69},
          new int[] {102, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 70},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 104, 33},
          new int[] {105, 105, 71},
          new int[] {106, 114, 33},
          new int[] {115, 115, 72},
          new int[] {116, 65535, -30},
        },
        new int[][] {
          new int[] {11, 107, -21},
          new int[] {108, 108, 73},
          new int[] {109, 65535, -28},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 111, 33},
          new int[] {112, 112, 74},
          new int[] {113, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 75},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 76},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 77},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 78},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 111, -48},
          new int[] {112, 112, 79},
          new int[] {113, 65535, -48},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 80},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 81},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 82},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 96, -26},
          new int[] {97, 97, 83},
          new int[] {98, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 104, -46},
          new int[] {105, 105, 84},
          new int[] {106, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 104, -46},
          new int[] {105, 105, 85},
          new int[] {106, 65535, -61},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 86},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 87},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 119, 33},
          new int[] {120, 120, 88},
          new int[] {121, 65535, -21},
        },
        new int[][] {
          new int[] {9, 41, -40},
          new int[] {42, 42, 89},
          new int[] {43, 65535, 64},
        },
        new int[][] {
          new int[] {9, 41, 65},
          new int[] {42, 42, 90},
          new int[] {43, 65535, 65},
        },
        new int[][] {
          new int[] {48, 57, 66},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 107, -21},
          new int[] {108, 108, 91},
          new int[] {109, 65535, -28},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 101, -24},
          new int[] {102, 102, 92},
          new int[] {103, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 93},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 94},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 108, 33},
          new int[] {109, 109, 95},
          new int[] {110, 65535, -24},
        },
        new int[][] {
          new int[] {11, 98, -43},
          new int[] {99, 99, 96},
          new int[] {100, 65535, -43},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 97},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 99, -42},
          new int[] {100, 100, 98},
          new int[] {101, 65535, -42},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 99},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 100},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 99, -42},
          new int[] {100, 100, 101},
          new int[] {101, 65535, -42},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 102},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 59, -5},
          new int[] {63, 72, 33},
          new int[] {73, 73, 103},
          new int[] {74, 90, 33},
          new int[] {92, 65535, -5},
        },
        new int[][] {
          new int[] {9, 9, 104},
          new int[] {10, 10, 105},
          new int[] {11, 12, 104},
          new int[] {13, 13, 105},
          new int[] {14, 41, 104},
          new int[] {42, 42, 89},
          new int[] {43, 46, 104},
          new int[] {47, 47, 106},
          new int[] {48, 65535, 104},
        },
        new int[][] {
          new int[] {9, 41, 105},
          new int[] {42, 42, 90},
          new int[] {43, 46, 105},
          new int[] {47, 47, 107},
          new int[] {48, 65535, 105},
        },
        new int[][] {
          new int[] {11, 101, -24},
          new int[] {102, 102, 108},
          new int[] {103, 65535, -73},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 114, -30},
          new int[] {115, 115, 109},
          new int[] {116, 65535, -30},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 110},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 111},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 92, -5},
          new int[] {94, 102, 33},
          new int[] {103, 103, 112},
          new int[] {104, 122, 33},
          new int[] {124, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 113},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {9, 9, 114},
          new int[] {10, 10, 115},
          new int[] {11, 12, 114},
          new int[] {13, 13, 115},
          new int[] {14, 41, 114},
          new int[] {42, 42, 116},
          new int[] {43, 65535, 114},
        },
        new int[][] {
          new int[] {9, 41, 115},
          new int[] {42, 42, 117},
          new int[] {43, 65535, 115},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {11, 104, -46},
          new int[] {105, 105, 118},
          new int[] {106, 65535, -61},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 119},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 115, -23},
          new int[] {116, 116, 120},
          new int[] {117, 65535, -23},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 99, -42},
          new int[] {100, 100, 121},
          new int[] {101, 65535, -42},
        },
        new int[][] {
          new int[] {9, 65535, -106},
        },
        new int[][] {
          new int[] {9, 65535, -107},
        },
        new int[][] {
          new int[] {9, 41, -91},
          new int[] {42, 42, 116},
          new int[] {43, 65535, -91},
        },
        new int[][] {
          new int[] {9, 41, 105},
          new int[] {42, 42, 117},
          new int[] {43, 65535, -92},
        },
        new int[][] {
          new int[] {11, 113, -27},
          new int[] {114, 114, 122},
          new int[] {115, 65535, -27},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 123},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 114, -30},
          new int[] {115, 115, 124},
          new int[] {116, 65535, -30},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 125},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 115, -23},
          new int[] {116, 116, 126},
          new int[] {117, 65535, -23},
        },
        new int[][] {
          new int[] {11, 115, -23},
          new int[] {116, 116, 127},
          new int[] {117, 65535, -23},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 59, -5},
          new int[] {63, 66, 33},
          new int[] {67, 67, 128},
          new int[] {68, 78, 33},
          new int[] {79, 79, 129},
          new int[] {80, 90, 33},
          new int[] {92, 65535, -5},
        },
        new int[][] {
          new int[] {11, 107, -21},
          new int[] {108, 108, 130},
          new int[] {109, 65535, -28},
        },
        new int[][] {
          new int[] {11, 111, -48},
          new int[] {112, 112, 131},
          new int[] {113, 65535, -48},
        },
        new int[][] {
          new int[] {11, 110, -22},
          new int[] {111, 111, 132},
          new int[] {112, 65535, -26},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 133},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 114, -30},
          new int[] {115, 115, 134},
          new int[] {116, 65535, -30},
        },
        new int[][] {
          new int[] {11, 109, -19},
          new int[] {110, 110, 135},
          new int[] {111, 65535, -19},
        },
        new int[][] {
          new int[] {11, 100, -20},
          new int[] {101, 101, 136},
          new int[] {102, 65535, -44},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
        new int[][] {
          new int[] {11, 65535, -5},
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 43, 38, 39, 44, -1, 45, 22, 2, 7, 1, 37, 0, 36, 17, 40, 
        30, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 20, 
        13, 39, 39, -1, 42, 45, -1, -1, 39, 39, 39, 39, 39, 39, 39, 39, 
        39, 39, 19, 21, 39, 3, 39, 39, 5, 39, 29, 39, 39, 39, 39, 39, 
        -1, -1, 41, 24, 39, 11, 6, 39, 39, 28, 39, 4, 39, 39, 10, 39, 
        33, 39, 27, 39, 39, 39, 39, 26, 39, -1, -1, 31, 16, 15, 39, 14, 
        32, 39, 9, 39, 39, 23, 25, 39, -1, -1, 45, 46, 39, 39, 39, 12, 
        34, 39, -1, -1, -1, -1, 39, 35, 8, 39, 39, 39, 39, 39, 18, 39, 
        39, 39, 39, 39, 39, 39, 39, 39, 39, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
